### PR TITLE
Added Estimation Abstract to Main Readme

### PR DESCRIPTION
**Pull request by ologandavid**
Still need to add a link to the abstract in a future commit

### CODE REVIEW

**Comment by ologandavid** [comment]
Link Added, Needs Approval

**Comment by ologandavid** [comment]
Bump @ardalantj

**Review by ardalantj — APPROVED** [review]

**Comment by ologandavid** [comment]
@selvingarciag96 Can you help me approve these changes?

**Review by selvingarciag96 — APPROVED** [review]
Read the update added to the README for estimation

**Pull request merged**
